### ISSUE TITLE
Cannot refer to node_modules in monorepo

### ISSUE THREAD

**Issue by wshino** [matter-labs/foundry-zksync#411] opened 2024-06-04 16:52 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.0.2 (d94bab2 2024-06-04T00:25:36.901896000Z)

### What command(s) is the bug in?

forge build --zksync

### Operating System

macOS (Apple Silicon)

### Describe the bug

It seems that current foundy-zksync cannot resolve some files in monorepo's node_modules dir in `forge build --zksync`.

```
Error (6275): Source "../node_modules/forge-std/src/Base.sol" not found: File outside of allowed directories. The following are allowed: ".".
ParserError: Source "../node_modules/forge-std/src/Base.sol" not found: File outside of allowed directories. The following are allowed: ".".
  --> ../node_modules/forge-std/src/Test.sol:27:1:
   |
27 | import {TestBase} from "./Base.sol";
```

I have foundry.toml properly configured with lib and fs_permissions. I did not encounter this error before; adding allow_paths did not help. Perhaps these settings are not crossing over to foundy-zksync properly? Is there a way to resolve this?
The build succeeds properly in `forge build` command (normal foundry).

I created an example repo created by `forge init`
If you do `forge build --zksync` in the contracts dir here, you should be able to reproduce the above problem.
https://github.com/wshino/foundry-zksync-example

Thank you.

**Comment by elfedy** [comment] 2024-06-24 17:15
There seem to be two issues here:
* `allow_paths` was not being forwarded correctly (fixed in: https://github.com/Moonsong-Labs/compilers/pull/6)
* solc sometimes adds sources via import callbacks and that is still not supported by zksolc (see: https://github.com/matter-labs/era-compiler-solidity/issues/98). This happens in foundry for example when there are libraries living outside of the project root, which will make solc readd the dependency as a different source unit even though it is already specified in the input (For example, for a library, there will be two source units on the output one named `/home/user/project/libraries/Lib.sol` and other `../libraries/Lib.sol`) and that makes zksolc fail when looking for its key on the input

**Comment by koloz193** [comment] 2024-06-24 22:42
ok so i tested it and with your setup it does in fact fail. if you move the contents of contracts one level up and add the deps to that higher level package.json it should work. The other option could be to install deps with forge install vs yarn

**Comment by wshino** [comment] 2024-08-29 17:38
@Jrigada Thank you so much! I've just tested the behavior on foundry-zksync-example. But `forge build --zksync` is still failing. I already installed foundry zksync which commit is `c8e23ef319b58008adba8fe947e1717caca64ed7` is that correct?
Is there any configuration to be added?

**Comment by Jrigada** [comment] 2024-08-29 18:35
Is the error you are getting still the same as before? In particular
```
Error (6275)
ParserError: Source "../node_modules/forge-std/src/safeconsole.sol" not found: File outside of allowed directories. The following are allowed: ".".
```

**Comment by wshino** [comment] 2024-08-29 23:43
Yes, somehow it's still happening. I'll send you more details if you want.

**Comment by Jrigada** [comment] 2024-08-30 18:38
Yes no problem. I am not able to reproduce it even though I reset my environment. Do you have any other change in your repo? With the latest commit on main of foundry zksync it should work.

**Comment by koloz193** [comment] 2024-09-04 20:54
I was able to recreate the issue and figure out a workaround. Essentially you'll need to create a symlink within `contracts` to the parent folder's `node_modules` with `ln -s node_modules contracts/node_modules` and then update the `foundry.toml` to look like 
```
[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
allow_paths = ["zkout"]
fs_permissions = [
    { access = "read", path = "../node_modules" },
]

solc = "0.8.23"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
```

and `remappings.txt` to be:
```
@openzeppelin/=node_modules/@openzeppelin
@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable
forge-std/=node_modules/forge-std/src
```

then compilation should work

**Comment by wshino** [comment] 2024-09-05 04:22
@koloz193 Thank you so much. Actually we are using the workaround that you posted.

**Closed** 2024-09-05 13:45 UTC
Labels: T-bug
