### ISSUE TITLE
Unable to verify. Solidity Compilation Error: Invalid EVM version requested

### ISSUE THREAD

**Issue by fedealconada** [matter-labs/foundry-zksync#679] opened 2024-10-30 12:24 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.0.2 (ac5feb1 2024-10-30T00:25:47.390509000Z)

### What command(s) is the bug in?

forge verify-contract

### Operating System

macOS (Apple Silicon)

### Describe the bug

Trying to deploy a contract (with `pragma solidity 0.6.12`) and then verify it throws this error. Happening both with Sophon's explorer (zkSync explorer fork) and with Sophon's Etherscan explorer.

On Sophon explorer:
```
forge verify-contract 0xeC719f51A9D4E1588DBd3B37493e13a7936d90BF ./contracts/util/SignatureChecker.sol:SignatureChecker --watch --verifier zksync --verifier-url https://api-explorer-verify.testnet.sophon.xyz/contract_verification --zksync
Start verifying contract `0xeC719f51A9D4E1588DBd3B37493e13a7936d90BF` deployed on mainnet

Submitting verification for [contracts/util/SignatureChecker.sol:SignatureChecker] at address 0xeC719f51A9D4E1588DBd3B37493e13a7936d90BF.
Verification submitted successfully. Verification ID: 360
Checking verification status for ID: 360 using verifier: zksync at URL: https://api-explorer-verify.testnet.sophon.xyz/contract_verification
Error:
Verification error: Compilation error
```

On Sophon's Etherscan explorer: 
```
forge verify-contract 0xeC719f51A9D4E1588DBd3B37493e13a7936d90BF ./contracts/util/SignatureChecker.sol:SignatureChecker --watch --rpc-url testnet --zksync
Start verifying contract `0xeC719f51A9D4E1588DBd3B37493e13a7936d90BF` deployed on 531050104

Submitting verification for [contracts/util/SignatureChecker.sol:SignatureChecker] 0xeC719f51A9D4E1588DBd3B37493e13a7936d90BF.
Submitted contract for verification:
	Response: `OK`
	GUID: `upqq9h9gnkspcislzuxyq7kmskcvjrrrn15mjf6ktfcm9sb1sv`
	URL: https://api-sepolia.sophscan.xyz/address/0xec719f51a9d4e1588dbd3b37493e13a7936d90bf
Contract verification status:
Response: `NOTOK`
Details: `Pending in queue`
Contract verification status:
Response: `NOTOK`
Details: `Fail - Unable to verify. Solidity Compilation Error: Invalid EVM version requested.`
Error:
Checking verification result failed

Context:
- Contract failed to verify.
```

This is my foundry.toml

```
[rpc_endpoints]
testnet = "${TESTNET_RPC_URL}"

[etherscan]
testnet = { key = "${ETHERSCAN_API_KEY}", url = "${TESTNET_VERIFIER_URL}", chain = 531050104 }
```

Contract being verified is:

```
pragma solidity 0.6.12;

import { ECRecover } from "./ECRecover.sol";
import { IERC1271 } from "../interface/IERC1271.sol";

/**
 * @dev Signature verification helper that can be used instead of `ECRecover.recover` to seamlessly support both ECDSA
 * signatures from externally owned accounts (EOAs) as well as ERC1271 signatures from smart contract wallets.
 *
 * Adapted from https://github.com/OpenZeppelin/openzeppelin-contracts/blob/21bb89ef5bfc789b9333eb05e3ba2b7b284ac77c/contracts/utils/cryptography/SignatureChecker.sol
 */
library SignatureChecker {
    /**
     * @dev Checks if a signature is valid for a given signer and data hash. If the signer is a smart contract, the
     * signature is validated against that smart contract using ERC1271, otherwise it's validated using `ECRecover.recover`.
     * @param signer        Address of the claimed signer
     * @param digest        Keccak-256 hash digest of the signed message
     * @param signature     Signature byte array associated with hash
     */
    function isValidSignatureNow(
        address signer,
        bytes32 digest,
        bytes memory signature
    ) external view returns (bool) {
        if (!isContract(signer)) {
            return ECRecover.recover(digest, signature) == signer;
        }
        return isValidERC1271SignatureNow(signer, digest, signature);
    }

    /**
     * @dev Checks if a signature is valid for a given signer and data hash. The signature is validated
     * against the signer smart contract using ERC1271.
     * @param signer        Address of the claimed signer
     * @param digest        Keccak-256 hash digest of the signed message
     * @param signature     Signature byte array associated with hash
     *
     * NOTE: Unlike ECDSA signatures, contract signatures are revocable, and the outcome of this function can thus
     * change through time. It could return true at block N and false at block N+1 (or the opposite).
     */
    function isValidERC1271SignatureNow(
        address signer,
        bytes32 digest,
        bytes memory signature
    ) internal view returns (bool) {
        (bool success, bytes memory result) = signer.staticcall(
            abi.encodeWithSelector(
                IERC1271.isValidSignature.selector,
                digest,
                signature
            )
        );
        return (success &&
            result.length >= 32 &&
            abi.decode(result, (bytes32)) ==
            bytes32(IERC1271.isValidSignature.selector));
    }

    /**
     * @dev Checks if the input address is a smart contract.
     */
    function isContract(address addr) internal view returns (bool) {
        uint256 size;
        assembly {
            size := extcodesize(addr)
        }
        return size > 0;
    }
}

```

**Comment by nbaztec** [comment] 2024-10-30 12:50
I see it's using solidity 0.6.x you may wanna try setting a valid evm version with `--evm-version`. Perhaps `istanbul`.

**Comment by fedealconada** [comment] 2024-10-30 12:55
Amazing, that worked for Etherscan @nbaztec but not for Sophon's zkSync explorer fork...

```
forge verify-contract 0xeC719f51A9D4E1588DBd3B37493e13a7936d90BF ./contracts/util/SignatureChecker.sol:SignatureChecker --watch --verifier zksync --verifier-url https://api-explorer-verify.testnet.sophon.xyz/contract_verification --zksync --evm-version istanbul
Start verifying contract `0xeC719f51A9D4E1588DBd3B37493e13a7936d90BF` deployed on mainnet

Submitting verification for [contracts/util/SignatureChecker.sol:SignatureChecker] at address 0xeC719f51A9D4E1588DBd3B37493e13a7936d90BF.
Verification submitted successfully. Verification ID: 361
Checking verification status for ID: 361 using verifier: zksync at URL: https://api-explorer-verify.testnet.sophon.xyz/contract_verification
Error:
Verification error: Deployed bytecode is not equal to generated one from given source
```

**Comment by fedealconada** [comment] 2024-10-30 13:08
I don't think `--solc` is a valid argument

**Comment by nbaztec** [comment] 2024-10-30 15:39
Is the artifact/version obtained from the `zkout` directory? Zksolc uses its own solc and I'm wondering it there's an issue there around which version is being forced.

**Comment by fedealconada** [comment] 2024-10-30 15:45
`zkout` does not have the versions, my foundry.toml has this config:
```
out = "artifacts/foundry"
```
So, I'm getting it from that directory. This is the file I'm looking at: `SignatureChecker.metadata.json`

```
{
  "compiler": {
    "version": "0.6.12+commit.27d51765"
  },
  "language": "Solidity",
  "output": {
    "abi": [
      {
        "inputs": [
          {
            "internalType": "address",
            "name": "signer",
            "type": "address"
          },
          {
            "internalType": "bytes32",
            "name": "digest",
            "type": "bytes32"
          },
          {
            "internalType": "bytes",
            "name": "signature",
            "type": "bytes"
          }
        ],
        "stateMutability": "view",
        "type": "function",
        "name": "isValidSignatureNow",
        "outputs": [
          {
            "internalType": "bool",
            "name": "",
            "type": "bool"
          }
        ]
      }
    ],
    "devdoc": {
      "kind": "dev",
      "methods": {
        "isValidSignatureNow(address,bytes32,bytes)": {
          "details": "Checks if a signature is valid for a given signer and data hash. If the signer is a smart contract, the signature is validated against that smart contract using ERC1271, otherwise it's validated using `ECRecover.recover`.",
          "params": {
            "digest": "Keccak-256 hash digest of the signed message",
            "signature": "Signature byte array associated with hash",
            "signer": "Address of the claimed signer"
          }
        }
      },
      "version": 1
    },
    "userdoc": {
      "kind": "user",
      "methods": {},
      "version": 1
    }
  },
  "settings": {
    "remappings": [
      "@ensdomains/=node_modules/@ensdomains/",
      "@openzeppelin/=node_modules/@openzeppelin/",
      "@solidity-parser/=node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/",
      "ds-test/=lib/forge-std/lib/ds-test/src/",
      "eth-gas-reporter/=node_modules/eth-gas-reporter/",
      "forge-std/=lib/forge-std/src/",
      "hardhat/=node_modules/hardhat/"
    ],
    "optimizer": {
      "enabled": true,
      "runs": 10000000
    },
    "metadata": {
      "bytecodeHash": "ipfs"
    },
    "compilationTarget": {
      "contracts/util/SignatureChecker.sol": "SignatureChecker"
    },
    "evmVersion": "istanbul",
    "libraries": {
      "SignatureChecker": "0xdbd3ff2bc63d6e969acb5333918ac29c4bd40179"
    }
  },
  "sources": {
    "contracts/interface/IERC1271.sol": {
      "keccak256": "0x8accb9f93dcd398e5c84cb80010de808cf5092cebfa823b3d7c4b8e5b2bcf672",
      "urls": [
        "bzz-raw://5b695059d7f0ba51bf58a3713683a892051078fdaabf37bbb8673614542b3267",
        "dweb:/ipfs/QmRQoDkk2serLRyjnKFD2ynXnu8b4JyAix9DnBcwkdyL9n"
      ],
      "license": "Apache-2.0"
    },
    "contracts/util/ECRecover.sol": {
      "keccak256": "0xedf59af6c5998f9e4b0791cd79122a759a1d80a38453053df77838914dd1294d",
      "urls": [
        "bzz-raw://318c71b3f57477e7178b1a9eef86176ead3876bc7e2c196c312b07e6e79dd8f0",
        "dweb:/ipfs/Qmer6yrZ39T1XWRtwCgz6DJE1ojT2eRKihsFfZJHzfErFk"
      ],
      "license": "Apache-2.0"
    },
    "contracts/util/SignatureChecker.sol": {
      "keccak256": "0x89181a5d7440ce21492c5023ab98357c76e3de81ffc376dfda3983997a70728a",
      "urls": [
        "bzz-raw://8a9e3c2176362b727900c001dd6625fb2c12773475effdb4e24ff44ce56654e3",
        "dweb:/ipfs/QmNsdopHx3ZN7iANvTVJ1wH49MogQEgsUqBBD44USqUQS9"
      ],
      "license": "Apache-2.0"
    }
  },
  "version": 1
}
```

**Comment by nbaztec** [comment] 2024-10-30 16:40
The `out` is the solc artifact, the `zkout` is the artifact depoyed to zksync and I'm assuming it used a specific version of zksolc-solc that is not being picked up in the verification. We'll take a deeper look and try to reproduce it on our end.

**Comment by fedealconada** [comment] 2024-10-30 16:42
Perfect, thank you. Bear in mind that I have been able to verify on Sophon's Etherscan but only couldn't on Sophon's zkSync explorer. Keep me posted please 🙏🏻

**Comment by Jrigada** [comment] 2024-10-31 15:03
Hey @fedealconada, I tried deploying and verifying the contract on my end using the Sophon Explorer. The deployment was successful, but the Explorer didn’t detect the bytecode as identical to yours, so it didn’t autoverify it. Could you try redeploying and verifying the new deployment?

[Here’s](https://explorer.testnet.sophon.xyz/address/0x2EaCc6c9a8436568E2d1dFadC98e6bbDEA48772c#contract) the deployment I did. I used the contract you provided and obtained the dependency contracts from other repositories.

**Comment by fedealconada** [comment] 2024-10-31 15:05
But did you fix anything on your end that it may make the verification now pass?

**Comment by Jrigada** [comment] 2024-10-31 15:07
No, I just created a new project with the contract you provided and then did `forge create` to deploy and `forge verify-contract`.

**Comment by fedealconada** [comment] 2024-10-31 15:09
but did you manage to verify your contract?

**Comment by Jrigada** [comment] 2024-10-31 15:15
Yes! here is the link to the explorer
https://explorer.testnet.sophon.xyz/address/0x2EaCc6c9a8436568E2d1dFadC98e6bbDEA48772c#contract

**Comment by fedealconada** [comment] 2024-11-01 11:27
hmm.. i'm still not being able, you can find the contract [here](https://github.com/circlefin/stablecoin-evm/blob/master/contracts/util/SignatureChecker.sol) in case you want to reproduce it with the same I have. If you clone the repo as is, you will have some issues to make it compile on zkSync (I think you only need to remove the calls to `selfdestruct`)

**Comment by fedealconada** [comment] 2024-11-01 12:53
By the way, it's not only the SignatureChecker the one I'm having issues with, just any contract within that repo :/ @Jrigada

**Comment by Jrigada** [comment] 2024-11-01 14:17
Hey Fede,
It looks like there are quite a few issues beyond the self-destruct error. This repo also seems to be affected by a [bug](https://github.com/matter-labs/era-compiler-solidity/issues/188#issuecomment-2451284064) in zksolc, which is resolved in version 1.5.7, although we haven't yet added support for that version. Could you provide an isolated, reproducible example repo containing only the SignatureChecker and dependencies? This would help reduce the variables and differences between our test cases. We will merge 1.5.7 support as soon as possible from our side.

**Comment by dutterbutter** [comment] 2024-11-04 02:18
@fedealconada it may be resolved with https://github.com/matter-labs/foundry-zksync/pull/690. Can you please try again to confirm? 

The TL;DR of the issue experienced by others that may be the same here, was during verification is an `evm_version` was not explicitly supplied the verification request assumed an evm version which was incorrect for older solc versions.

**Comment by dutterbutter** [comment] 2024-11-15 15:41
Closing with #690 and staleness

**Closed by dutterbutter** 2024-11-15 15:41 UTC
Labels: bug 🐛, p2 🟡
