### ISSUE TITLE
forge test panics

### ISSUE THREAD

**Issue by aliXsed** [matter-labs/foundry-zksync#426] opened 2024-06-13 02:51 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.0.2 (3891bdab 2024-06-13T02:23:06.383872039Z)

### What command(s) is the bug in?

forge test
forge build
forge clean

### Operating System

macOS (Apple Silicon)

### Describe the bug

The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Location: crates/cli/src/opts/build/paths.rs:71

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  <empty backtrace>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
[1]    174648 IOT instruction (core dumped)  forge test --match-path test/myTest.t.sol

**Comment by aliXsed** [comment] 2024-06-13 02:57
I think it was caused by my terminal calling `forge` from a folder that was already removed.

**Comment by Jrigada** [comment] 2024-06-17 14:10
Hey @aliXsed thanks for raising this issue! 
Could you confirm that the issue is resolved? It seems to be caused but what you are mentioning but just to be sure. In the case this happens again we can take a look from our side. 
I'll wait for your answer before closing the issue just to be sure.

**Comment by aliXsed** [comment] 2024-06-17 22:31
@Jrigada Yes it was caused but what I mentioned and did not happen after I changed directory.

**Closed** 2024-06-18 13:55 UTC
Labels: T-bug
