### ISSUE TITLE
chore(repo): update foundry-compilers to 0.3.13 to support 0.8.25 solc

### ISSUE THREAD

**Issue by plonukob** [matter-labs/foundry-zksync#383] opened 2024-05-17 06:17 UTC
The same update to 0.3.13 is needed here as in https://github.com/matter-labs/foundry-zksync/issues/341
https://github.com/matter-labs/foundry-zksync/blob/13497a550e4a097c57bec7430435ab810a6d10fc/Cargo.lock#L4546
https://github.com/matter-labs/foundry-zksync/blob/13497a550e4a097c57bec7430435ab810a6d10fc/Cargo.toml#L141

**Comment by dutterbutter** [comment] 2024-05-17 16:33
Duplicate of #341

**Closed by dutterbutter** 2024-05-17 16:33 UTC

**Comment by plonukob** [comment] 2024-05-17 19:15
https://github.com/matter-labs/foundry-zksync/blob/13497a550e4a097c57bec7430435ab810a6d10fc/Cargo.lock#L4546

This is exactly what is not a duplicate. https://github.com/matter-labs/foundry-zksync/issues/341 only fixed:
https://github.com/matter-labs/foundry-zksync/blob/13497a550e4a097c57bec7430435ab810a6d10fc/Cargo.toml#L141


@dutterbutter
