### ISSUE TITLE
Failed to compile with zksolc: Could not assign standard_json to writer

### ISSUE THREAD

**Issue by PatrickAlphaC** [matter-labs/foundry-zksync#331] opened 2024-04-19 03:04 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.0.2 (1e5e102 2024-04-18T13:02:37.531316000Z)

### What command(s) is the bug in?

build

### Operating System

macOS (Intel)

### Describe the bug

1. Setup a new project

```
mkdir new-dir
cd new-dir
forge init
```

2. Build it

```
forge build --zksync
```

You'll get this:

```
[⠰] Compiling...
[⠢] Compiling 2 files with 0.8.25
[⠰] Solc 0.8.25 finished in 1.80s
Compiler run successful!
Error: 
Failed to compile with zksolc: Could not assign standard_json to writer
```

**Comment by elfedy** [comment] 2024-04-19 10:58
@PatrickAlphaC I had this same issue the other day. It was due `zksolc` not being compatible with `solc-0.8.25`. However forge is resolving the solc version to use, it is selecting  `0.8.25` vs something compatible (`0.8.24` or lower).
Maybe try checking the logs with `RUST_LOG=trace forge build` to check where it is taking solc from then try to remove it and add `solc-0.8.24` instead

**Comment by mm-zk** [comment] 2024-04-19 13:42
Thanks @elfedy - the full workaround that worked for me:

* remove the 0.8.25 solc ($HOME/.local/share/svm/0.8.25) - for other systems, you can run `RUST_LOG=trace forge build` and see where solc is located
* run with flag to set older version `FOUNDRY_SOLC_VERSION=0.8.24  forge build  --zksync`

**Comment by elfedy** [comment] 2024-06-17 17:47
The original reported issue is known to happen when zksolc tries to use a solc version it doesn't support. For now, the way to troubleshoot is either try to use a newer version of zksolc via the zksolc option in foundry toml, or try to specify an older version of solc that the current version. Running forge with RUST_LOG=trace may help to determine which versions of each compiler are being used. The UX should be improved when solving https://github.com/matter-labs/foundry-zksync/issues/208 and https://github.com/matter-labs/foundry-zksync/issues/428.
Closing as this has been stale for a while. If the issue is still there and it's not due to what has been stated above, please reopen and we can try to troubleshoot.

**Closed by elfedy** 2024-06-17 17:47 UTC
Labels: T-bug

**Comment by PatrickAlphaC** [comment] 2024-06-18 14:19
The 2 issues logged do not address this issue with the console output, and will continue to be a thorn.

**Comment by elfedy** [comment] 2024-06-18 14:24
@PatrickAlphaC could you detail how https://github.com/matter-labs/foundry-zksync/issues/428 is not what you intend? The idea would be to error with a message about incompatible compiler versions and possible actions on how to solve them. Maybe we could clarify what you thing is missing in that issue instead?

**Comment by PatrickAlphaC** [comment] 2024-06-20 14:57
Ah sorry, I missed it. Yep, that is good!
