### ISSUE TITLE
`forge script` reverts likely due to incorrect data construction 

### ISSUE THREAD

**Issue by smol-ninja** [matter-labs/foundry-zksync#339] opened 2024-04-23 19:40 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.0.2 (532ef5e 2024-04-22T00:22:39.180249000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

`forge script` is likely constructing the incorrect data leading to the following error:

```bash
Sending transactions [0 - 0].
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: JsonRpcClientError(JsonRpcError(JsonRpcError { code: 3, message: "execution reverted", data: Some(String("0x")) }))
Location: crates/forge/bin/cmd/script/broadcast.rs:669
```

Check out the warp block: https://app.warp.dev/block/F0yTm0BDEqyyYdN327UZuF

Repo: https://github.com/sablier-labs/v2-core/

**Comment by andreivladbrg** [comment] 2024-04-23 20:02
+1 Same issues faced by me

**Comment by dutterbutter** [comment] 2024-04-24 13:03
@smol-ninja thanks for posting the issue, it should not panic here so we will be investigating.

**Comment by dutterbutter** [comment] 2024-04-25 16:16
@andreivladbrg can you link the HH implementation. Will be quicker to debug. I am able to debug this now.

When you say "...uses an unknown opcode" - can you elaborate. Are you using an unknown opcode?

**Comment by dutterbutter** [comment] 2024-04-25 16:22
nvm found the hh branch. Will investigate.

**Comment by smol-ninja** [comment] 2024-04-25 16:25
> Are you using an unknown opcode?

No, we are not using any special opcode. We saw this bug when we tried to deploy contracts with Foundry. But we thought it may be a bug with Foundry itself. So Andrei ported the code to HH and saw the same error again. That's why we are guessing if it's related to one of the libraries that we import.

**Comment by dutterbutter** [comment] 2024-04-25 16:41
@smol-ninja @andreivladbrg still need to investigate Foundry but the HH implementation worked fine for me with minor changes. See below details:

- Fork with changes: https://github.com/sablier-labs/v2-core/commit/1509209475fc95ea6e3f71a89053adb279fbfcdd

**Successful HH deployment / verification output:**
```
bun run hardhat deploy-zksync --script deploy.ts --network zkSyncTestnet
┌─────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────┐
│     (index)     │                                              Values                                              │
├─────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────┤
│    contract     │ 'SablierV2Comptroller & SablierV2NFTDescriptor & SablierV2LockupDynamic & SablierV2LockupLinear' │
│     chainId     │                                               300                                                │
│     network     │                                         'zkSyncTestnet'                                          │
│ deployerAddress │                           '0x7182fA7dF76406ffFc0289f36239aC1bE134f305'                           │
└─────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────┘
SablierV2Comptroller deployed to: 0x07CC4deb26e09EfEf5eFF579b9Cb2cC4616cc8D1

Verifying contract...
Your verification ID is: 11531
Contract successfully verified on zkSync block explorer!
SablierV2NFTDescriptor deployed to: 0xD479fd546cb4fCe8509Ee4B48D29B4b0C5324287

Verifying contract...
Your verification ID is: 11532
Contract successfully verified on zkSync block explorer!
SablierV2LockupDynamic deployed to: 0xE40C678FdC1211156FA531251E758650F2BAcD43

Verifying contract...
Your verification ID is: 11533

Your verification request has been sent, but our servers are currently overloaded and we could not confirm that the verification was successful.
Please try one of the following options:
  1. Use the your verification request ID (11533) to check the status of the pending verification process by typing the command 'yarn hardhat verify-status --verification-id 11533'
  2. Manually check the contract's code on the zksync block explorer: https://explorer.zksync.io/
  3. Run the verification process again

Contract successfully verified on zkSync block explorer!
SablierV2LockupLinear deployed to: 0xB959FE756Be7Df5118f089571e3b156a0C4e4af2

Verifying contract...
Your verification ID is: 11534

Your verification request has been sent, but our servers are currently overloaded and we could not confirm that the verification was successful.
Please try one of the following options:
  1. Use the your verification request ID (11534) to check the status of the pending verification process by typing the command 'yarn hardhat verify-status --verification-id 11534'
  2. Manually check the contract's code on the zksync block explorer: https://explorer.zksync.io/
  3. Run the verification process again

Contract successfully verified on zkSync block explorer!
```

**Comment by andreivladbrg** [comment] 2024-04-25 16:44
Indeed, it works for the testnet. But when trying to deploy on the mainnet, it doesn't: https://app.warp.dev/block/R8pSjMJQWIljGSczzTNmTy

It also works with Foundry for the testnet.

**Comment by dutterbutter** [comment] 2024-04-25 16:45
ahhh interesting....

**Comment by dutterbutter** [comment] 2024-04-25 18:44
I was able to reproduce, and its certainly a weird issue as it works locally, testnet, forked mainnet but not on mainnet. Investigating the contract further as it seems thats where the issue may be. Will provide an update if I find anything.

**Comment by dutterbutter** [comment] 2024-04-25 19:02
@smol-ninja interesting, for me `SablierV2Comptroller` gets deployed, and verified fine. But then I hit the error during `SablierV2NFTDescriptor` deployment with:

```
Error: execution reverted (no data present; likely require(false) occurred ...
```

I never get to `SablierV2LockupDynamic` or `SablierV2LockupLinear`  deployment...

**Comment by smol-ninja** [comment] 2024-04-25 19:54
Oh. For me, with `foundry-zksync`, I was able to deploy `SablierV2NFTDescriptor` as well. But hit that  `Some(String("0x"))` error with `LockupLinear` and `LockupDynamic`. I now think `Some(String("0x"))` is foundry version of HH's no data present.

Could it be related to RPC nodes? (I am coming from the point that sometimes `SablierV2NFTDescriptor` gets deployed and sometimes it doesn't so could be related to RPCs)

**Comment by dutterbutter** [comment] 2024-04-25 19:58
I got it working !!!

**Comment by dutterbutter** [comment] 2024-04-25 20:01
Had to deploy the SVG libraries first, typically we should have seen the compiler complain about these during compilation. Why it did not, I will have to investigate.

But mainnet output:

```
┌─────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────┐
│     (index)     │                                              Values                                              │
├─────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────┤
│    contract     │ 'SablierV2Comptroller & SablierV2NFTDescriptor & SablierV2LockupDynamic & SablierV2LockupLinear' │
│     chainId     │                                               324                                                │
│     network     │                                         'zkSyncMainnet'                                          │
│ deployerAddress │                           '0xFac041BCF2c4b43319c2C0a39ABA53F4CbE44Fe5'                           │
└─────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────┘
NFTSVG deployed to: 0x232f9F448590308acB4A2d08360Ca377e8d87fAb
SVGElements deployed to: 0x064fF5DDc4d6746fa09aB42A4f671e34aeCee4eE
SablierV2Comptroller deployed to: 0xD302AF3c16DC00Cb7b6E7976eA7BeAdba3A466B5

Verifying contract...
Your verification ID is: 61426
Contract successfully verified on zkSync block explorer!
SablierV2NFTDescriptor deployed to: 0xA53121afA76d665FEF26B62dC6AC23FE45dF1116

Verifying contract...
Your verification ID is: 61427
Contract successfully verified on zkSync block explorer!

SablierV2LockupDynamic deployed to: 0x3e076cFDA872A906F549dB819e7edC048963AfB0

Verifying contract...
Your verification ID is: 61428

Your verification request has been sent, but our servers are currently overloaded and we could not confirm that the verification was successful.
Please try one of the following options:
  1. Use the your verification request ID (61428) to check the status of the pending verification process by typing the command 'yarn hardhat verify-status --verification-id 61428'
  2. Manually check the contract's code on the zksync block explorer: https://explorer.zksync.io/
  3. Run the verification process again

Contract successfully verified on zkSync block explorer!
SablierV2LockupLinear deployed to: 0xbf16A3472b6659360f1A589C99A18a32d7e27825

Verifying contract...
Your verification ID is: 61429
Contract successfully verified on zkSync block explorer!
```

Deploy script:
```
import { Addressable } from "ethers";
import hre from "hardhat";
import { Deployer } from "@matterlabs/hardhat-zksync";
import { Wallet, Provider } from "zksync-ethers";

export default async function () {
  const network = await hre.network.config;
  const networkName = await hre.network.name;
  const chainId = Number(network.chainId);

  const provider = new Provider(hre.network.config.url);
  const deployerAddressPV = new Wallet(process.env.PV_KEY as string).connect(provider);
  const deployerAddress = deployerAddressPV.address;

  if (!deployerAddress) {
    console.error("Please set the PV_KEY in your .env file");
    return;
  }

  console.table({
    contract: "SablierV2Comptroller & SablierV2NFTDescriptor & SablierV2LockupDynamic & SablierV2LockupLinear",
    chainId: chainId,
    network: networkName,
    deployerAddress: deployerAddress,
  });

  const deployer = new Deployer(hre, deployerAddressPV);

  const artifactSVG = await deployer.loadArtifact("NFTSVG");
  const artifactSVGElements = await deployer.loadArtifact("SVGElements");
  const artifactComptroller = await deployer.loadArtifact("SablierV2Comptroller");
  const artifactNFTDescriptor = await deployer.loadArtifact("SablierV2NFTDescriptor");
  const artifactLockupDynamic = await deployer.loadArtifact("SablierV2LockupDynamic");
  const artifactLockupLinear = await deployer.loadArtifact("SablierV2LockupLinear");

  const safeMultisig = "0xaFeA787Ef04E280ad5Bb907363f214E4BAB9e288";

  const svg = await deployer.deploy(artifactSVG, []);
  console.log("NFTSVG deployed to:", svg.target);
  const svg_element = await deployer.deploy(artifactSVGElements, []);
  console.log("SVGElements deployed to:", svg_element.target);

  // Deploy the SablierV2Comptroller contract
  const comptroller = await deployer.deploy(artifactComptroller, [safeMultisig]);

  const comptrollerAddress =
    typeof comptroller.target === "string" ? comptroller.target : comptroller.target.toString();
  console.log("SablierV2Comptroller deployed to:", comptrollerAddress);
  await verifyContract(comptrollerAddress, [safeMultisig]);

  const nftDescriptor = await deployer.deploy(artifactNFTDescriptor, []);
  const nftDescriptorAddress =
    typeof nftDescriptor.target === "string" ? nftDescriptor.target : nftDescriptor.target.toString();
  console.log("SablierV2NFTDescriptor deployed to:", nftDescriptorAddress);
  await verifyContract(nftDescriptorAddress, []);

  // Deploy the SablierV2LockupDynamic contract
  const dynamic = await deployer.deploy(artifactLockupDynamic, [
    safeMultisig,
    comptrollerAddress,
    nftDescriptorAddress,
    "324",
  ]);
  const dynamicAddress = typeof dynamic.target === "string" ? dynamic.target : dynamic.target.toString();
  console.log("SablierV2LockupDynamic deployed to:", dynamicAddress);
  await verifyContract(dynamicAddress, [safeMultisig, comptrollerAddress, nftDescriptorAddress, "324"]);

  // Deploy the SablierV2LockupLinear contract
  const linear = await deployer.deploy(artifactLockupLinear, [safeMultisig, comptrollerAddress, nftDescriptorAddress]);
  const linearAddress = linear.target;
  console.log("SablierV2LockupLinear deployed to:", linearAddress);
  await verifyContract(linearAddress, [safeMultisig, comptrollerAddress, nftDescriptorAddress]);
}

const verifyContract = async (contractAddress: string | Addressable, verifyArgs: string[]): Promise<boolean> => {
  console.log("\nVerifying contract...");
  await new Promise((r) => setTimeout(r, 20000));
  try {
    await hre.run("verify:verify", {
      address: contractAddress.toString(),
      constructorArguments: verifyArgs,
      noCompile: true,
    });
  } catch (e) {
    console.log(e);
  }
  return true;
};

```

**Comment by smol-ninja** [comment] 2024-04-25 20:26
Yes I got it except I didn't understand why did you have to deploy the libraries separately? They are a part of `SablierV2NFTDescriptor` and ain't required to be deployed separately.

**Comment by dutterbutter** [comment] 2024-04-25 20:29
Still investigating the reasoning and asked our platform team to review, as it does not really fit into the requirements for non-inlinable libraries described [here](https://docs.zksync.io/build/tooling/hardhat/compiling-libraries.html).

**Comment by smol-ninja** [comment] 2024-04-25 20:46
Yes. We will follow your lead and make the deployment. So I guess we cannot deploy it with foundry because foundry does not allow deploying libraries separately if they do not contain public or external functions, which is true in our case.

In your method, you deployed them separately using hardhat which is weird but great it worked. And during the deployments of `SablierV2NFTDescriptor`, the libraries still got embedded in the bytecode of `SablierV2NFTDescriptor` so `SablierV2NFTDescriptor` is not going to make delegate call to the deployed libraries. Hmm..

Anyways since it worked thank you so much for the help for your help 💚.

**Comment by dutterbutter** [comment] 2024-04-25 20:51
@smol-ninja not a problem! We will be investigating it further so will provide an update when I can.

**Comment by andreivladbrg** [comment] 2024-04-25 20:54
@dutterbutter thank you for the help and effort 🙏🏻

Looking forward to hearing from you. I'm super curious about this library situation - it just seems weird to me for now.

**Comment by andreivladbrg** [comment] 2024-04-26 10:42
Just wanted to say that I also tried to deploy them again using your approach (deploying the libraries) and had no succes for `SablierV2LockupDynamic` and `SablierV2LockupLinear` but for `SablierV2NFTDescriptor` it worked.

I also tried to deploy `Helpers` lib which is used in both lockup contracts.

**Comment by smol-ninja** [comment] 2024-04-26 10:49
Adding a point here: I was able to deploy `SablierV2NFTDescriptor` without deploying libraries separately. It worked for me in the foundry setup too. 

Also `SablierV2LockupDynamic` and `SablierV2LockupLinear` do not depend on those SVG libraries at all. So may be thats why this is not working for us. @dutterbutter are you able to deploy the contracts again? May be it was one time (just guessing).

**Comment by andreivladbrg** [comment] 2024-04-26 12:40
Merged your changes into our repo: https://github.com/sablier-labs/v2-core/pull/910

But no succes: https://app.warp.dev/block/TGKda5YweBv53alWCZzrfw

**Comment by andreivladbrg** [comment] 2024-04-26 12:51
I am noticing a difference in the import path in the contract deployed on mainnet.

Referring to this line:

https://github.com/sablier-labs/v2-core/blob/c167d50189ca11b67156cf8eabe371c2de638abf/contracts/SablierV2LockupLinear.sol#L7

[Onchain](https://explorer.zksync.io/address/0xDB01feEA0c6C3d9377a5a346e96730dD64a0DB8e#contract), it appears like this:

<img width="663" alt="image" src="https://github.com/matter-labs/foundry-zksync/assets/99738872/456e9942-2a97-4e60-9d86-300c638e2e43">

Could it be related to remappings, and it can't figure out where that contract is?

**Comment by andreivladbrg** [comment] 2024-04-26 13:01
YESS! This was the reason why it reverted (Foundry remappings vs Hardhat remappings)...

I [removed](https://github.com/sablier-labs/v2-core/commit/5ff6b463cb36014562711c27caea71d57c90d910) the @prb/math remapping and it worked: https://app.warp.dev/block/a84UReQJG24ncPo23ZSVvk

**Comment by dutterbutter** [comment] 2024-04-26 13:01
Yes, it looks like it was from remappings:

`@prb/math/=node_modules/@prb/math/` 

Although I had not made any changes to the contracts. Perhaps something hardhat-foundry plugin produced?

**Comment by dutterbutter** [comment] 2024-04-26 13:01
> YESS! This was the reason why it reverted (Foundry remappings vs Hardhat remappings)...
> 
> I [removed](https://github.com/sablier-labs/v2-core/commit/5ff6b463cb36014562711c27caea71d57c90d910) the @prb/math remapping and it worked: https://app.warp.dev/block/a84UReQJG24ncPo23ZSVvk

Amazing 🎉  👍  Glad it worked!!

**Comment by andreivladbrg** [comment] 2024-04-26 13:14
Though, why did the testnet deployment work without removing the remapping, but it didn’t work for the mainnet? @dutterbutter

**Closed** 2024-04-29 08:25 UTC
Labels: T-bug

**Comment by smol-ninja** [comment] 2024-05-07 16:30
@dutterbutter do the fork tests in `foundry-zksync` follow zksync op codes for gas estimation?
