### ISSUE TITLE
`deal(address token, address who, uint256 give)` fails with `No storage use detected for target`

### ISSUE THREAD

**Issue by webthethird** [matter-labs/foundry-zksync#337] opened 2024-04-23 17:52 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.0.2 (532ef5e 2024-04-22T00:21:35.201114596Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

When I attempt to deal ERC20 tokens to an address using `deal(address token, address who, uint256 give)` after forking zkSync Era mainnet, I get the following error and trace (where 0x3355df6D4c9C3035724Fd0e3914dE96A5a83aaf4 is USDC deployed on zkSync Era):
```
  [163415] LimitOrderTest::test_DealUSDC()
    ├─ [0] 0x3355df6D4c9C3035724Fd0e3914dE96A5a83aaf4::balanceOf(LimitOrderTest: [0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496]) [staticcall]
    │   └─ ← 0
    ├─ [0] VM::record()
    │   └─ ← ()
    ├─ [0] 0x3355df6D4c9C3035724Fd0e3914dE96A5a83aaf4::balanceOf(LimitOrderTest: [0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496]) [staticcall]
    │   └─ ← 0
    ├─ [0] VM::accesses(0x3355df6D4c9C3035724Fd0e3914dE96A5a83aaf4)
    │   └─ ← [], []
    └─ ← revert: stdStorage find(StdStorage): No storage use detected for target.
```
The Solidity code is as follows (note: I get the same error no matter which token I use):
```solidity
contract ForkTest is Test {
    /* fork */
    uint256 public eraFork;

    /* fork addresses */
    address constant USDC = 0x3355df6D4c9C3035724Fd0e3914dE96A5a83aaf4;

    /* contracts */
    IERC20Metadata public usdc;

    function setUp() public virtual {
        /* initialize fork */
        eraFork = vm.createFork("https://mainnet.era.zksync.io");
        vm.selectFork(eraFork);

        /* get existing deployments */
        usdc = IERC20Metadata(USDC);
    }

    function test_DealUSDC() public {
        deal(address(usdc), address(this), 1 ether);
        ...
    }
}
```
I am using the forge-std library v1.8.0, where `deal` is defined in StdCheats.sol as:
```solidity
    // Set the balance of an account for any ERC20 token
    // Use the alternative signature to update `totalSupply`
    function deal(address token, address to, uint256 give) internal virtual {
        deal(token, to, give, false);
    }

    function deal(address token, address to, uint256 give, bool adjust) internal virtual {
        // get current balance
        (, bytes memory balData) = token.staticcall(abi.encodeWithSelector(0x70a08231, to));
        uint256 prevBal = abi.decode(balData, (uint256));

        // update balance
        stdstore.target(token).sig(0x70a08231).with_key(to).checked_write(give);

        // update total supply
        if (adjust) {
            (, bytes memory totSupData) = token.staticcall(abi.encodeWithSelector(0x18160ddd));
            uint256 totSup = abi.decode(totSupData, (uint256));
            if (give < prevBal) {
                totSup -= (prevBal - give);
            } else {
                totSup += (give - prevBal);
            }
            stdstore.target(token).sig(0x18160ddd).checked_write(totSup);
        }
    }
```

**Comment by dutterbutter** [comment] 2024-04-23 19:17
@webthethird really appreciate the bug report. We will investigate the issue, to speed up our investigation do you happen to have a repo link or a minimal reproducible example that we can quickly run to reproduce?

**Comment by webthethird** [comment] 2024-04-24 16:10
> To confirm you ran with the `--zksync` flag?

Indeed, I did.

> do you happen to have a repo link or a minimal reproducible example that we can quickly run to reproduce?

The repo I'm working on is private for now, but I will put together a minimal example to share here by EOD.

**Comment by webthethird** [comment] 2024-04-24 17:14
@dutterbutter 
https://github.com/webthethird/min-reproducible-deal-token-bug-zksync-foundry

**Comment by Karrq** [comment] 2024-05-28 22:13
Hey, I couldn't help but notice that your issue was opened just before we [merged](https://github.com/matter-labs/foundry-zksync/pull/328) something that might fix your issue. Could you try again with a newer version of our `forge`?

**Comment by Karrq** [comment] 2024-06-05 17:00
Hey @webthethird I tried your min-reproducible repo and I think the issue is fixed.

```
Ran 1 test for test/Dealer.t.sol:DealerTest
[PASS] test_DealTokens() (gas: 180024)
Suite result: ok. 1 passed; 0 failed; 0 skipped; finished in 396.29ms (271.60ms CPU time)
```

Thanks for the report! Feel free to reopen this issue if the error persist on your side.

**Closed by Karrq** 2024-06-05 17:00 UTC
Labels: cheatcode
